### Site info:
title: M的奇葩漂流
tagline: 人生如茶，空杯以对。对程序的态度，正如对生活的态度。
author: Zheng Yu
email: michaelcoco1991@gmail.com
description: "Michael的技术与生活博客" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Michael,blog,IT,javascript,front-end,internet"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://axemea.github.io" # the base hostname & protocol for your site


### Personal info and site tools info:
twitter_username: zheng yu
github_username:  axemea
disqus_shortname: axemea
favicon:     "/images/favicon.ico"
aboutme: 曾经，最苦恼的是，被别人称作安静的美男子。现在，最苦恼的是，特么的这些竟然是真的。待你下次的转身，我会果断抱住你，然后大声地说，我要全世界都知道，我只是一名前端工程师。  # these are shown on aboutme-sidebar.
aboutme_photo: https://avatars1.githubusercontent.com/u/4532661?v=3&s=460 # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Resent_Posts: "Resent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Resent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
#    - name: axemea
#      href: http://axemea.github.io
#      title: blog
#    - name: author's website
#      href: http://axemea.github.io/
#      title: Zheng yu's website


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
